
dist: trusty
language: java
jdk: openjdk8
install:
  - true
script:
  - mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify coveralls:report -P \!dependency-security-check 